#+title: notify-send-server
#+startup: fold indent
#+filetags: :github:project:

- Have you ever wanted to send a notification from a remote server to your local machine?
- If so, this [[https://babashka.org/][babashka]] script may be for you.

* Usage

** =bb server=
#+begin_src bash
bb server
#+end_src

*Run the server.*

- =bb server= listens on `/tmp/notify-send.sock` for [[https://github.com/edn-format/edn][EDN]] expressions and passes them to the notify function in `notify.clj`.

** =bb client=
#+begin_src bash
# Send a message as an EDN expression
echo '["hello"]' | bb client
# Send a custom title and message
echo '["Custom Title" "Body of Message"]' | bb client
# Pass options to notify-send
echo '[{"-a" "Emacs *perl-live*" "--urgency" "critical"} "Crash" ' \
     \"$(date --utc --iso-8601=seconds)\" "]" | bb client
#+end_src

*Send a request to the server.*

- =bb client= reads one [[https://github.com/edn-format/edn][EDN]] expression and sends it to the server.
  + =[ "body" ]=
  + =[ "title" "body" ]=
  + =[ {"--option" "value" } "title" "body" ]= - The options should be options supported by [[https://manpages.ubuntu.com/manpages/noble/man1/notify-send.1.html][notify-send]].

** =bb ssh=
#+begin_src bash
env REMOTE=anon@remoteserver.org bb ssh
#+end_src

*Forward the local unix domain socket to the remote server.*

- Specify the user and server in the =REMOTE= environment variable.
- In the future, I may make the path to the Unix domain socket configurable.

Now this remote server can send notifications to the local server that's running the notify-send-server.  They make requests the exact same way, because the remote server will have its own unix domain socket which happens to forward to the local unix domain socket.

*NOTE*:  On the remote server, =/etc/ssh/sshd_config= may need to have =StreamLocalUnbindLink yes= added to it.  See this [[https://unix.stackexchange.com/a/429903][Unix StackExchange answer]] for more details.

** =bb autossh=
#+begin_src bash
env REMOTE=anon@remoteserver.org bb autossh
#+end_src

This works the same as `bb ssh`, but it uses [[https://github.com/Autossh/autossh][autossh]] instead to provide connection monitoring and automatic restarts.
